### ISSUE TITLE
Compiling Solution - Output Error - Parse error at "_DEPRECATE_TR1_NAMESPACE"

### ISSUE THREAD

**Issue by Langerz82** [ryzom/ryzomcore#589] opened 2020-02-14 10:35 UTC
I'm getting that error for a few of the projects. Any idea how to bypass the error?

``
1>Generating moc_crash_report_socket.cxx
1>:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/include/cstdin(37): Parse error at "_DEPRECATE_TR1_NAMESPACE"
1>D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1.
1>Done building project "crash_report.vcxproj" -- FAILED.
``

**Comment by kaetemi** [comment] 2020-03-06 21:42
Cannot reproduce.
What's your setup?

**Comment by kaetemi** [comment] 2020-03-29 17:25
Closing because there's no further update. Reopen if you have more info.

**Closed as completed by kaetemi** 2020-03-29 17:25 UTC
Labels: invalid
